<!DOCTYPE html>
<html>
<head>
	<title>IPN - Registro Jornadas </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="/css/datatables.css" media="all">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="js/datatables.js"></script>

    
	
  
  {% if ENV_DEVELOPMENT %}
  {% endif %}
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>
